# Generated by Django 4.2.7 on 2024-01-27 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0002_alter_ticket_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="support",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ساپورت",
            ),
        ),
    ]
