# Generated by Django 4.2.7 on 2024-01-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_support"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام ها",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
    ]
