# Generated by Django 4.2.7 on 2023-11-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project_procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rfp",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/rfps",
                        verbose_name="آر اف پی",
                    ),
                ),
                (
                    "confirm_proposal",
                    models.BooleanField(default=True, verbose_name="وضعیت پروپوزال"),
                ),
                (
                    "description_reject_proposal",
                    models.TextField(
                        blank=True, null=True, verbose_name="دلیل رد کردن پروپوزال"
                    ),
                ),
                (
                    "contract_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/contract",
                        verbose_name="قرارداد",
                    ),
                ),
                (
                    "payment_receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/payment",
                        verbose_name="رسید پرداخت",
                    ),
                ),
                (
                    "confirm_design",
                    models.BooleanField(default=True, verbose_name="وضعیت طراحی"),
                ),
                (
                    "description_reject_design",
                    models.TextField(
                        blank=True, null=True, verbose_name="دلیل رد کردن طراحی"
                    ),
                ),
                (
                    "proposal",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/proposals",
                        verbose_name="پروپوزال",
                    ),
                ),
                (
                    "contract",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/contract",
                        verbose_name="قرارداد",
                    ),
                ),
                (
                    "payment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/payment",
                        verbose_name="صورت حساب",
                    ),
                ),
                (
                    "confirm_contract",
                    models.BooleanField(default=True, verbose_name="وضعیت قرارداد"),
                ),
                (
                    "description_reject_contract",
                    models.TextField(
                        blank=True, null=True, verbose_name="دلیل رد کردن قرارداد"
                    ),
                ),
                (
                    "confirm_payment_receipt",
                    models.BooleanField(default=True, verbose_name="وضعیت رسید پرداخت"),
                ),
                (
                    "description_reject_payment_receipt",
                    models.TextField(
                        blank=True, null=True, verbose_name="دلیل رد کردن رسید پرداخت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "روند پروژه",
                "verbose_name_plural": "روند پروژه ها",
            },
        ),
    ]
