# Generated by Django 4.2.7 on 2023-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_procedure",
            name="project_title",
            field=models.CharField(
                default="پروژه جدید", max_length=200, verbose_name="عنوان پروژه"
            ),
        ),
    ]
