# Generated by Django 4.2.7 on 2023-12-05 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_project_procedure_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_procedure",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project_procedure",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
