# Generated by Django 4.2.7 on 2023-12-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_project_procedure_created_project_procedure_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project_procedure",
            options={
                "ordering": ["-created"],
                "verbose_name": "روند پروژه",
                "verbose_name_plural": "روند پروژه ها",
            },
        ),
        migrations.AlterField(
            model_name="project_procedure",
            name="confirm_contract",
            field=models.BooleanField(default=False, verbose_name="وضعیت قرارداد"),
        ),
        migrations.AlterField(
            model_name="project_procedure",
            name="confirm_design",
            field=models.BooleanField(default=False, verbose_name="وضعیت طراحی"),
        ),
        migrations.AlterField(
            model_name="project_procedure",
            name="confirm_payment_receipt",
            field=models.BooleanField(default=False, verbose_name="وضعیت رسید پرداخت"),
        ),
        migrations.AlterField(
            model_name="project_procedure",
            name="confirm_proposal",
            field=models.BooleanField(default=False, verbose_name="وضعیت پروپوزال"),
        ),
    ]
