# Generated by Django 4.2.7 on 2023-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_project_procedure_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industrial_park",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="شهرک صنعتی"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="اسم شرکت"),
                ),
                (
                    "ceo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام مدیر عامل",
                    ),
                ),
                (
                    "ceo_phone_nember",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="شماره تلفن مدیر عامل",
                    ),
                ),
                (
                    "factory_phone1",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="تلفن کارخانه شماره اول",
                    ),
                ),
                (
                    "factory_phone2",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="تلفن کارخانه شماره دوم",
                    ),
                ),
                (
                    "factory_phone3",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="تلفن کارخانه شماره سوم",
                    ),
                ),
                (
                    "telephoneـcentralـoffice",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="تلفن دفتر مرکزی",
                    ),
                ),
                (
                    "related_preson",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام فرد مرتبط",
                    ),
                ),
                (
                    "related_preson_phoneـnumber",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شماره موبایل افراد مرتبط",
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="وبسایت"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="فکس",
                    ),
                ),
                (
                    "tehran_fax",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="فکس تهران",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "گزینه اول"),
                            (2, "گزینه دوم"),
                            (3, "گزینه سوم"),
                            (4, "گزینه چهارم"),
                            (5, "گزینه پنجم"),
                        ],
                        max_length=1,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "اطلاعات شرکت",
                "verbose_name_plural": "اطلاعات شرکت",
                "ordering": ["-created"],
            },
        ),
        migrations.AlterField(
            model_name="project_procedure",
            name="contract_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/contract",
                verbose_name="ارسال اسکن قرارداد",
            ),
        ),
    ]
