# Generated by Django 4.2.7 on 2023-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_contactlist_alter_project_procedure_contract_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactlist",
            options={
                "ordering": ["-created"],
                "verbose_name": "اطلاعات شرکت",
                "verbose_name_plural": "اطلاعات شرکت ها",
            },
        ),
        migrations.AlterField(
            model_name="contactlist",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "گزینه اول"),
                    (2, "گزینه دوم"),
                    (3, "گزینه سوم"),
                    (4, "گزینه چهارم"),
                    (5, "گزینه پنجم"),
                ],
                null=True,
                verbose_name="وضعیت",
            ),
        ),
    ]
