# Generated by Django 4.2.7 on 2023-12-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_alter_contactlist_options_alter_contactlist_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactList",
        ),
    ]
